### ISSUE TITLE
Unable to load mods on Linux

### ISSUE THREAD

**Issue by AdivonSlav** [Shazbot/WH3-Mod-Manager#63]
I'm running PopOS 22.04 and tried running the mod manager through Steam's Proton compatibility layer. The mod manager runs, through the downloaded workshop mods never appear and downloading new ones through the mod manager does nothing (no downloads on Steam's end start). The folder paths seem to be correctly set, matching Proton's Z: drive path.

**Comment by jpw1991** [comment]
@AdivonSlav how did you fix this? Encountering the same problem

**Comment by tpkee** [comment]
Why can't people write the solution they found ffs

**Comment by tpkee** [comment]
nope, doesnt work at all

**Comment by tpkee** [comment]
> Hmm, wierd. Is it set as the Z folder as well in the mod manager's Configure Folder Locations? Do you see mods in the manager, does it generate the used_mods.txt file? What OS are you running and proton did you test on?

Since I ran it through Proton it should be the Z drive, yeah.

The manager doesn’t open at all and doesn’t log anything in particular. I used the proton experimental version on the exe (latest v from the release page) added to steam as a non-Steam game. I also tried to ran it on the prefix with proton tricks, tried to psss the steam compat env var as well but it doesn’t open. 

The OS is arch Linux with the zen kernel, wine staging. The 32bits libs are installed as well

**Comment by GalacticAdmiral** [comment]
This is wierd but i tried the latest build and used 7z to extract and got the same result as you. But when i used unzip it worked fine.

**Comment by tpkee** [comment]
> This is wierd but i tried the latest build and used 7z to extract and got the same result as you. But when i used unzip it worked fine.

This is crazy but I unzipped it with unzip and it works. I didn't add it as a non steam game though, i just used protontricks-launch to use the same prefix (it's in the protontricks package)

**Comment by GalacticAdmiral** [comment]
> because the app opens but it doesn’t load any font or anything else and the JavaScript mostly doesn’t work;

Just want to add i have the exact same problems after compiling, with no conclusive logs.
